apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
    master: 'true'
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
        master: 'true'
      annotations:
        scheduler.alpha.kubernetes.io/affinity: |
          {
            "podAntiAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": [
                {
                  "labelSelector": {
                    "matchLabels": {
                        "component": "elasticsearch",
                        "role": "master",
                        "master": "true"
                      }
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }
              ]
            }
          }
    spec:
      containers:
      - name: es-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: kayrus/docker-elasticsearch-kubernetes:2.4.4
        args:
        - /run.sh
        - -Des.path.conf=/etc/elasticsearch
        readinessProbe:
          tcpSocket:
            port: 9300
          timeoutSeconds: 1
          successThreshold: 3
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-cluster-name
        - name: NUMBER_OF_REPLICAS
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-number-of-replicas
        - name: NODE_MASTER
          value: 'true'
        - name: NODE_DATA
          value: 'false'
        - name: HTTP_ENABLE
          value: 'false'
        - name: ES_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-master-heap
        - name: ES_CLIENT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-client-endpoint
        - name: "NETWORK_HOST"
          value: "_site_,_lo_,eth0:ipv4"
        ports:
        - name: transport
          containerPort: 9300
          protocol: TCP
        volumeMounts:
        - name: es-config
          mountPath: /etc/elasticsearch
        # /pre-stop-hook.sh hook is already used in /run.sh on pod shutdown
        #lifecycle:
        #  preStop:
        #    exec:
        #      command:
        #      - '/pre-stop-hook.sh'
      # Wait infinite, we have to move all indices from the current node and only after that shut down the pod
      terminationGracePeriodSeconds: 31557600
      volumes:
      - name: es-config
        configMap:
          name: es-config
