apiVersion: v1
kind: Service
metadata:
  name: solr-lb
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
    - name: solr
      port: 8983
      targetPort: 8983
  selector:
    app: solr-nginx
  type: LoadBalancer
 
