cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${HOSTNAME}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log
  plugins: /elasticsearch/plugins
  work: /data/work

bootstrap.mlockall: true

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

cloud:
  kubernetes:
    service: ${DISCOVERY_SERVICE}
    namespace: ${NAMESPACE}
discovery:
  type: kubernetes
  zen:
    minimum_master_nodes: ${NUMBER_OF_MASTERS}

index:
  number_of_shards: ${NUMBER_OF_SHARDS}
  number_of_replicas: ${NUMBER_OF_REPLICAS}

# This is the requirement for Kibana scripted_fields when you wish to use Groovy scripts in search and data aggregation.
# HACK: when you create a scripted_field, its default language is set to "expression", but you can easily set "groovy" in POST request for this field
# These options are useful for https://github.com/stormpython/heatmap Kibana plugin.
script:
  engine:
    groovy:
      inline:
        search: true
        aggs: true
