apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    component: elasticsearch
    master: 'true'
spec:
  selector:
    component: elasticsearch
    master: 'true'
  ports:
  - name: transport
    port: 9300
    protocol: TCP
