apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    k8s-app: kibana
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-v5
  labels:
    k8s-app: kibana
    version: v5
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: kibana
        version: v5
    spec:
      containers:
      - name: kibana
        image: kayrus/docker-kibana-kubernetes:5.2.2
        #image: docker.elastic.co/kibana/kibana:5.2.2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 5601
          timeoutSeconds: 1
          successThreshold: 1
        env:
          - name: ELASTICSEARCH_URL
            valueFrom:
              configMapKeyRef:
                name: es-env
                key: es-client-endpoint
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: SERVER_BASEPATH
            value: "/kibana"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
