apiVersion: v1
kind: Service
metadata:
  name: neo4j-cluster
  labels:
    app: neo4j
spec:
  ports:
  - port: 7474
    targetPort: 7474
    name: api
  clusterIP: None
  selector:
    app: neo4j
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  serviceName: neo4j-cluster
  replicas: 3
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: neo4j
        image: neo4j
        imagePullPolicy: Always
        ports:
        - containerPort: 7474
          name: "api"
        ports:
        - containerPort: 7687
          name: "bolt"
        volumeMounts:
        - name: dataclaim
          mountPath: /data
        resources:
          requests:
            memory: 4000Mi
  volumeClaimTemplates:
  - metadata:
      name: dataclaim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
